import axios from 'axios';
import * as ti from 'technicalindicators';
import { MarketDataEngine } from './marketData.js';

/**
 * Represents a comprehensive trade signal generated by the SignalGenerator.
 */
export interface TradeSignal {
  symbol: string;
  signal: 'BUY' | 'SELL' | 'HOLD';
  confidence: number;
  technicals: {
    rsi: number;
    macd: { MACD: number; signal: number; histogram: number };
    bollinger: { upper: number; middle: number; lower: number };
  };
  sentiment: {
    score: number;
    headlines: string[];
    signal: string;
  };
  patterns: string[];
}

/**
 * Generator for quantitative trade signals combining technical indicators,
 * chart patterns, and news sentiment.
 */
export class SignalGenerator {
  private marketData: MarketDataEngine;
  private newsApiKey: string | undefined;

  /**
   * Creates an instance of SignalGenerator.
   * @param newsApiKey Optional API key for news sentiment analysis. If not provided, it will try to use process.env.NEWS_API_KEY.
   */
  constructor(newsApiKey?: string) {
    this.marketData = new MarketDataEngine();
    this.newsApiKey = newsApiKey || process.env.NEWS_API_KEY;
  }

  /**
   * Generates a comprehensive BUY/SELL/HOLD signal for a symbol.
   * @param symbol Stock symbol
   * @param timeframe Timeframe for analysis (default: 1d)
   * @returns Signal object with confidence score and supporting data
   */
  async generateSignal(symbol: string, timeframe: string = '1d'): Promise<TradeSignal> {
    const historicalData = await this.marketData.getHistoricalData(symbol, new Date(Date.now() - 30 * 24 * 60 * 60 * 1000)); // Last 30 days
    const prices = historicalData.map(d => d.close);

    // 1. Technical Indicators
    const rsi = ti.rsi({ values: prices, period: 14 }).pop() || 50;
    const macdResult = ti.macd({
      values: prices,
      fastPeriod: 12,
      slowPeriod: 26,
      signalPeriod: 9,
      SimpleMAOscillator: false,
      SimpleMASignal: false,
    }).pop() as any || { MACD: 0, signal: 0, histogram: 0 };

    const bbResult = ti.bollingerbands({
      values: prices,
      period: 20,
      stdDev: 2,
    }).pop() || { upper: 0, middle: 0, lower: 0 };

    // 2. Sentiment Analysis
    const sentiment = await this.analyzeSentiment(symbol);

    // 3. Pattern Detection
    const patterns = this.detectPatterns(prices);

    // 4. Logic for Signal
    let score = 0;
    
    // RSI logic
    if (rsi < 30) score += 30; // Oversold (Bullish)
    else if (rsi > 70) score -= 30; // Overbought (Bearish)

    // MACD logic
    if (macdResult && (macdResult as any).histogram !== undefined && (macdResult as any).histogram > 0) score += 20;
    else score -= 20;

    // Sentiment logic
    score += sentiment.score * 50; // Sentiment score is between -1 and 1

    // Pattern logic
    if (patterns.includes('Double Bottom') || patterns.includes('Inverted Head and Shoulders')) score += 15;
    if (patterns.includes('Double Top') || patterns.includes('Head and Shoulders')) score -= 15;

    // Determine signal
    let signal: 'BUY' | 'SELL' | 'HOLD' = 'HOLD';
    if (score > 40) signal = 'BUY';
    else if (score < -40) signal = 'SELL';

    const confidence = Math.min(Math.abs(score), 100);

    return {
      symbol,
      signal,
      confidence,
      technicals: {
        rsi,
        macd: {
          MACD: macdResult.MACD || 0,
          signal: macdResult.signal || 0,
          histogram: macdResult.histogram || 0
        },
        bollinger: {
          upper: bbResult.upper || 0,
          middle: bbResult.middle || 0,
          lower: bbResult.lower || 0
        },
      },
      sentiment,
      patterns,
    };
  }

  async analyzeSentiment(symbol: string): Promise<{ score: number; headlines: string[]; signal: string }> {
    if (!this.newsApiKey || this.newsApiKey === 'your_news_api_key_here') {
      return { score: 0, headlines: ['NewsAPI key not configured'], signal: 'Neutral' };
    }

    try {
      const query = symbol.split('.')[0];
      const response = await axios.get(`https://newsapi.org/v2/everything`, {
        params: {
          q: query,
          apiKey: this.newsApiKey,
          language: 'en',
          sortBy: 'publishedAt',
          pageSize: 5,
        },
      });

      const articles = response.data.articles || [];
      const headlines = articles.map((a: any) => a.title);

      // Simple keyword-based sentiment analysis
      let score = 0;
      const positiveWords = ['buy', 'growth', 'profit', 'surge', 'bull', 'up', 'high', 'win'];
      const negativeWords = ['sell', 'loss', 'drop', 'bear', 'down', 'low', 'fail', 'crash'];

      headlines.forEach((h: string) => {
        const words = h.toLowerCase().split(' ');
        words.forEach(w => {
          if (positiveWords.includes(w)) score += 0.1;
          if (negativeWords.includes(w)) score -= 0.1;
        });
      });

      return {
        score: Math.max(-1, Math.min(1, score)),
        headlines,
        signal: score > 0.3 ? 'Bullish' : score < -0.3 ? 'Bearish' : 'Neutral',
      };
    } catch (error: any) {
      console.error(`Error fetching news for ${symbol}:`, error instanceof Error ? error.message : String(error));
      return { score: 0, headlines: [], signal: 'Neutral' };
    }
  }

  /**
   * Performs technical chart pattern recognition on price data.
   * Detects: Double Top/Bottom, Head and Shoulders.
   * @param prices Array of closing prices
   * @returns List of detected patterns
   */
  private detectPatterns(prices: number[]): string[] {
    const patterns = [];
    if (prices.length < 20) return [];

    const last = prices[prices.length - 1];
    const prev = prices[prices.length - 2];

    // Simple Double Top/Bottom detection
    const peaks = [];
    const troughs = [];

    for (let i = 1; i < prices.length - 1; i++) {
      if (prices[i] > prices[i - 1] && prices[i] > prices[i + 1]) peaks.push({ val: prices[i], pos: i });
      if (prices[i] < prices[i - 1] && prices[i] < prices[i + 1]) troughs.push({ val: prices[i], pos: i });
    }

    if (peaks.length >= 2) {
      const p1 = peaks[peaks.length - 1];
      const p2 = peaks[peaks.length - 2];
      if (Math.abs(p1.val - p2.val) / p1.val < 0.02) patterns.push('Double Top');
    }

    if (troughs.length >= 2) {
      const t1 = troughs[troughs.length - 1];
      const t2 = troughs[troughs.length - 2];
      if (Math.abs(t1.val - t2.val) / t1.val < 0.02) patterns.push('Double Bottom');
    }

    // Simple Head and Shoulders (Bullish/Bearish)
    if (peaks.length >= 3) {
      const p3 = peaks[peaks.length - 1]; // Right Shoulder
      const p2 = peaks[peaks.length - 2]; // Head
      const p1 = peaks[peaks.length - 3]; // Left Shoulder
      if (p2.val > p1.val && p2.val > p3.val && Math.abs(p1.val - p3.val) / p1.val < 0.05) {
        patterns.push('Head and Shoulders');
      }
    }

    return patterns;
  }
}
